### PR TITLE
Remove absolute path to Base.lproj file in example project.

### PR DESCRIPTION
**Pull request by chrsmys**
screen shot 2016-03-10 at 9 41 52 am

### CODE REVIEW

**Comment by biscuitehh** [comment]
@chrsmys this should be fixed on the develop branch

**Comment by ianterrell** [comment]
@eriklamanna make the default branch `develop` to help?

**Comment by chrsmys** [comment]
Thought I was on develop... Nothing to see here

**Comment by eriklamanna** [comment]
I have updated the default to develop.  There is also currently a very large PR with lots of fixes in it waiting for finished review.

**Pull request closed without merging**
